src/org/openbravo/erpCommon/ad_forms/AcctServer.java
Add support for showing success message without lines in fact acct. When you create a template for accounting and not generate any lines before showing a error message with the correct text. Now showing the success message with the correct text
=> Issue #11: Add support for fact acct without lines

src/org/openbravo/erpCommon/ad_forms/AcctServer.java
EPL-275: The exception error is printed when the accounting process fails, instead of just printing the exception.
=> Issue #23:Improve error messages in the post/unpost process

src/org/openbravo/erpCommon/ad_actionButton/Posted.java
EPL-383: Add 'else if' deleted for a Sonar comment
=> Issue #70: Roll back change in Posted button logic to avoid error

build.gradle, build.xml, src-util/buildvalidation/build.xml, src/build.xml
The modifications made in this pull request correspond to the solution of issue #222.
The src/build.xml file, specifically the compileSqlc task, has been modified, changing the path to the classpath, now the path is project.class.path.full, this reference is defined within the build.xml file in the root of the project.
In addition, a new task is added which can be used to display the content of the classpath
=> Issue #222: modified CompileSqlc task,included class.path.full

src/org/openbravo/erpCommon/ad_callouts/SL_Order_Product.java
It was detected that the problem in the SL_Order_Product callout occurs due to a division by 0 in the discount calculation. This occurs when the price in the rate is 0.
Validation was added so that when this case occurs, now when the price in the rate is 0 the calculated discount will also be 0
=> Issue #224: Error adding line in sales order

modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/main/ob-standard-view.js
This error happens when the parent tab shows a message and a child that is from the same entity (like the Business Partner window) is refreshed. This fix prevents the hide of the message bar in the parent tab.
=> Issue #260: prevent hide message bar when refresh child tab

pipelines/unittests/JenkinsfileOracle
Introduce a lock to avoid concurrent builds and resolve pipeline conflicts.
=> Hotfix ETO-279: Prevent Oracle pipeline concurrency conflicts

src/org/openbravo/costing/AverageAlgorithm.java, src/org/openbravo/costing/CostingUtils.java
EPL-1196: Include product.getName() in OBException
=> Issue #281: AverageAlgorithm class can be improved by showing the product.getName() on the OBException

modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/process/ob-parameter-window-view.js
EPL-1197.
(26/01) - With the implementation of Actions, now the Object returned from the AddPaymentActionHandler is an ActionResult. This causes the properties added as "false" are not included in the response, it just avoids adding at least they were "true".
Arriving at the JS (modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/process/ob-parameter-window-view.js) this response (data) doesn't have the properties needed to be checked, they are "undefined" and comparing "undefined === false" is not the same that "false === false", so I have changed the validation to check for undefined too.
(29/01) - Change the logic of the validation to avoid being confusing.
=> Issue #282: Change the validation to check for undefined too

modules_core/com.smf.jobs.defaults/src-db/database/sourcedata/AD_TABLE.xml
EPL-1266: The process was missing the case for 'After Order Delivered' invoice term.
=> Issue #308: Fixed 'Generate invoices from orders' process

src/org/openbravo/erpCommon/ad_forms/UpdateReferenceData_data.xsql
EPL-1472: this change will prevent inactive organizations from appearing in the Organization selector of the 'Enterprise Module Management' window
=> Issue #388: Filter out inactive Orgs from 'Module Management' window

.github/workflows/build.yml, build.gradle, gradle.properties.template
Rename Sonar github action
> [!IMPORTANT]
> This branch is created as a “hotfix” but it is an enhancement to include coverage analysis in Jenkins.
=> Hotfix ETO-325: Add sonarqube properties

modules_core/com.smf.securewebservices/src/com/smf/securewebservices/service/SecureJsonDataService.java, modules_core/com.smf.securewebservices/web/com.smf.securewebservices/doc/doc.yaml
EPL-1535: The URL parameter name was changed in order to match with the parameter name itself.
=> Issue #418: Change the parameter name on the URL

src-test/src/org/openbravo/test/accounting/PostedNoDocConfigTest.java
ETP-166: The crash caused by the testDiscountWithoutDocTypeConfigured test when trying to remove the document type has been fixed, and improvements have been made to the accounting tests for Internal consumption. Specifically, unnecessary commits have been removed, modularity improvements, cleanup blocks and documentation in the methods.
=> Issue #448: Refactored accounting tests in Internal consumption

modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/process/ob-parameter-window-view.js
ETP-459: After the inclusion of the File Upload reference, BaseActionHandlers that do not contain parameters of the FileItemForm type do not complete their execution correctly due to a bad implementation in the ob-parameter-window-view.js class. Corrections have been made to solve this problem.
=> Issue #496: Fixed BaseActionHandler not ending

src/org/openbravo/erpCommon/businessUtility/CancelAndReplaceUtils.java, src/org/openbravo/erpCommon/businessUtility/CreateReplacementOrderExecutor.java
ETP-826: When a document number contains middle dashes due to the configuration of its prefix, problems arise when calculating the document number for cancellation. This improvement supports this case.
=> Issue #547: Support for middle dash in cancel and replace

pipelines/unittests/JenkinsfileOracle
An error has been corrected in the agent definition, since it had been missing : in one of the environment variables
=> Feature ETP-125: fix oracle SID variable in JenkinsfileOracle

pipelines/unittests/Jenkinsfile, pipelines/unittests/JenkinsfileOracle
Stack updated to work with java 17.0.3, postgres 16 and tomcat 9.0.98
=> Feature ETP-1157: Update stack and docker image in testing pipelines 

modules_core/org.openbravo.client.application/src/org/openbravo/client/application/report/BaseReportActionHandler.java
- No new imports or dependencies were added or removed.
- No endpoints were added, modified, or deleted.
- **Method Modified**: `protected JSONObject doExecute(Map<String, Object> parameters, String content)`
- **Change**: The method call to `getResponseBuilder().retryExecution().showResultsInProcessView().build()` has been modified to `getResponseBuilder().retryExecution().build()`. The `showResultsInProcessView()` method is no longer part of the method chain.
- No changes in types or interfaces affecting the public API.
- **Breaking Change**: The removal of `showResultsInProcessView()` in the response building process affects how results are presented. Previously, results were shown in the process view, which is no longer the case.
**Before Change:**
```java
JSONObject result = …
```
=> Feature ETP-1184: Fix UI issue in Advanced Reports

modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/ProcessInvoiceUtil.java, src/org/openbravo/erpCommon/ad_forms/AcctServer.java
- No new imports or dependencies added or removed.
- No endpoints were added, modified, or deleted.
- No method signatures were changed.
- No changes in types or interfaces that affect the public API.
- A condition within the method in `AcctServer` was modified:
- **Previous Condition:** `psdPrevious.getOrderPaymentSchedule() == null`
- **Updated Condition:** `psdPrevious.getOrderPaymentSchedule() == null && BigDecimal.ZERO.compareTo(paymentDetail.getFinPayment().getAmount()) != 0`
- **Impact:** This change ensures that the logic only applies when the payment amount is not zero, which could affect the flow of payment calculations.
**Usage Example:**
If you rely on the previous behavior where the condition did not check for non-zero amounts, you need to verify your logic to ensure it …
=> Issue #519: Prevent duplicate sum of payment lines in Z payments acct

modules_core/com.smf.securewebservices/web/com.smf.securewebservices/doc/index.html
- **Added:** `js-yaml` library imported in `index.html` for parsing YAML files.
- **No endpoint changes** (new, modified, or deleted) reported in this update.
- **Modified Method:**
- **Previous Implementation:**
```javascript
const ui = SwaggerUIBundle({
url: "doc.yaml",
dom_id: '#swagger-ui',
deepLinking: true,
presets: [
SwaggerUIBundle.presets.apis,
SwaggerUIStandalonePreset
],
plugins: [
SwaggerUIBundle.plugins.DownloadUrl
],
layout: "StandaloneLayout"
})
```
- **Updated Implementation:**
```javascript
fetch('doc.yaml')
.then(response => response.text())
.then(yamlText => {
const spec = jsyaml.load(yamlText);
spec.servers = [{ url: apiUrl }];
SwaggerUIBundle({
spec: spec,
dom_id: '#swagger-ui',
deepLinking: true,
presets: [SwaggerUIBundle.presets.apis],
plugins: …
```
=> Issue #578: Add dynamic url logic for Swagger UI

src-db/database/model/triggers/C_CANCELPRICEAD_TO_INVOICE.xml, src-db/database/sourcedata/AD_ELEMENT.xml
- No changes to imports or dependencies affecting the public API.
- No endpoint changes affecting the public API.
- No method changes affecting the public API.
- **Field Name Update**: The field name `Cancel Promotions` has been updated to `Cancel Discounts Promotions` across various XML schema definitions. This change affects the following files:
- `AD_ELEMENT.xml`
- `AD_FIELD.xml`
- **Trigger Added**: A new database trigger `C_CANCELPRICEAD_TO_INVOICE` has been added to the `C_INVOICELINE` table. The trigger fires before insert, update, and delete operations. It sets the `cancelpricead` field to 'Y' if the corresponding `c_orderline_id` has `cancelpricead` set to 'Y' in `c_orderline` table.
```sql
-- Example illustrating the effect of the new trigger
INSERT INTO C_INVOICELINE …
```
=> Feature ETP-1189: Add trigger to copy cancelpricead to invoices

modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/form/formitem/ob-formitem-fk-filter.js, modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/grid/ob-grid.js
- No new imports or dependencies were added or removed.
- No endpoint changes were made.
- **Modified Method**: The logic within `isc.OBGrid.addProperties` has been adjusted.
- **Previous Logic**: 
```javascript
if (criteria.criteria.get(i).fieldName !== 'id') {
return criteria;
}
```
- **Updated Logic**:
```javascript
if (criteria.criteria.get(i)?.fieldName !== 'id') {
return criteria.criteria.get(i);
}
```
- **Usage Example**:
The method now returns the specific criteria object instead of the entire `criteria` object when the `fieldName` is not `'id'`. This behavior change affects how criteria are processed:
```javascript
// Before
let result = processCriteria(criteria);
// result would be the entire criteria object
// After
let result = processCriteria(criteria);
// result is now the …
```
=> Issue #538: Prevent breaking criteria in grid

modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/filterexpression/TransactionAddPaymentDefaultValues.java, modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/filterexpression/TransactionAddPaymentDisplayLogics.java, modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/utility/APRMConstants.java, modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/utility/FIN_Utility.java
- No new imports or dependencies have been added or removed.
- No endpoints have been newly added, modified, or deleted.
- **Method**: `getDefaultIsSOTrx(Map<String, String> requestMap)`
- **Modification**: Changed the parameter access for context from `requestMap.get("context")` to `requestMap.get(APRMConstants.CONTEXT)`.
- **Method**: `getDefaultReceivedFrom(Map<String, String> requestMap)`
- **Modification**: Changed the parameter access for context from `requestMap.get("context")` to `requestMap.get(APRMConstants.CONTEXT)`.
- **Method**: `getOrganization(Map<String, String> requestMap)`
- **Modifications**:
- Changed the parameter access for context from `requestMap.get("context")` to `requestMap.get(APRMConstants.CONTEXT)`.
- Changed the parameter key from `"inpadOrgId"` to …
=> Issue #571: Credit selection available when adding payment

modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/ProcessInvoices.java, modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/ProcessInvoiceUtil.java, modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/ad_actionbutton/ProcessInvoice.java, src-db/database/model/functions/C_INVOICE_POST.xml, src-test/src/com/smf/jobs/defaults/ProcessInvoicesTest.java, src/org/openbravo/erpCommon/ad_actionButton/DocAction.html, src/org/openbravo/erpCommon/ad_actionButton/DocAction.xml
- No new imports or dependencies added or removed.
- No endpoints were added, modified, or deleted.
- **Method Modified**: `ProcessInvoiceUtil.process`
- **Old Signature**: 
```java
public OBError process(String strC_Invoice_ID, String strdocaction, String strVoidInvoiceDate, String strVoidInvoiceAcctDate, VariablesSecureApp vars, ConnectionProvider conn)
```
- **New Signature**:
```java
public OBError process(String strC_Invoice_ID, String strdocaction, String strVoidInvoiceDate, String strVoidInvoiceAcctDate, String strSupplierReference, VariablesSecureApp vars, ConnectionProvider conn)
```
- **Description**: Added parameter `String strSupplierReference` to facilitate supplier tracking.
- **Database Function Update**: `C_INVOICE_POST`
- Added variable `v_supplier_reference` of type …
=> Feature ETP-1185: Add Supplier Reference field when voiding invoice

src/org/openbravo/erpCommon/utility/reporting/printing/PrintController.java
ETP-1300: Fixed PDF concatenation problem when multiple documents are selected. Now concatReport(...) returns the ByteArrayOutputStream generated by the concatenation. This way, printReports(...) and finalizePrintResponse(...) use the same tempOutputStream, preventing it from arriving empty and ensuring that the downloaded PDF contains all selected documents.
=> Issue #639: Fix multi-pdf generation with shared ByteArrayOutputStream

src/org/openbravo/erpCommon/utility/reporting/printing/PrintController.java
ETP-1894: In order to avoid duplicating the attached files, we've added a validation to check if the docName was already added.
=> Issue #763: Adding a validation to check if the document is already shown.
