- modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/Post.java
> Issue #22: fix casting from Object to String

- src/org/openbravo/scheduling/DefaultJob.java
> Issue #36: Save process log on exceptions

- modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/Post.java
> Issue #22: change uncapitalize to getPropertyName by columnName

- modules_core/com.smf.jobs.defaults/web/com.smf.jobs.defaults/processRecords.js
EPL-338: Default value in drop-down fixed.
> Issue #33: Default value in drop-down fixed.

- modules_core/org.openbravo.client.application/web/org.openbravo.userinterface.smartclient/openbravo/skins/Default/org.openbravo.client.application/ob-form-styles.css
- modules_core/org.openbravo.client.application/web/org.openbravo.userinterface.smartclient/openbravo/skins/Default/org.openbravo.client.application/ob-form-styles.scss
- modules_core/org.openbravo.client.application/web/org.openbravo.userinterface.smartclient/openbravo/skins/Default/org.openbravo.client.application/ob-toolbar-styles.css
- modules_core/org.openbravo.client.application/web/org.openbravo.userinterface.smartclient/openbravo/skins/Default/org.openbravo.client.application/ob-toolbar-styles.scss
> Issue #32: Toolbar / Form / Popup buttons style fixed.

- modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/form/ob-view-form.js
- modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/process/ob-parameter-window-view.js
EPL-359: Multirecord process with 1 selection behaves as single record
> EPL-359 Multirecord processes cause loss of focus on records

- modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/Post.java
- src/org/openbravo/erpCommon/ad_forms/AcctServer.java
>  Issue #23: Improve error message handler

- modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/Post.java
- src/org/openbravo/erpCommon/ad_forms/AcctServer.java
> Issue #23: Improve error message handler

- src/org/openbravo/erpCommon/ad_actionButton/ActionButtonUtility.java
> Issue #60: add commit and start in session

- src/org/openbravo/configuration/ConfigurationApp.java
Update properties to use the specified bbdd url when the database is ORACLE
> Feature EPL-380: update properties

- build.xml
- src-trl/build.xml
- src/build.xml
Update build.xml files to recognize the GRADLE classpath of the JAR dependencies
> Feature EPL-366: Update build.xml

- src-db/database/model/triggers/M_ATTRIBUTEVALUE_TRG.xml
> Issue #52: Remove the conditions in M_ATTRIBUTEVALUE_TRG

- src/org/openbravo/erpCommon/ad_reports/ReportNotPosted.html
- src/org/openbravo/erpCommon/ad_reports/ReportNotPosted.java
EPL-372: add back button when an error with date ocurred
> Issue #55 add validation for date format and back button

- .github/workflows/build.yml
Remove analysis condition when push on the develop and main branches
> Feature ETO-67: Remove analysis condition

- build.gradle
- modules_core/org.openbravo.client.application/src/org/openbravo/client/application/window/OBViewParameterHandler.java
> Issue #103: Fix attach documents in window

- src/org/openbravo/base/secureApp/PopUp_Download.html
- src/org/openbravo/base/secureApp/PopUp_DownloadAndRefresh.html
- web/js/utils.js
> Issue #113: Fix downloading reports with Google Chrome

- src-db/database/model/functions/C_ORDER_POST1.xml
> Issue #128: not delete discount when close order

- modules_core/org.openbravo.client.application/src/org/openbravo/client/application/window/OBViewTab.java
> Issue #145: Fix error with accessing Goods Shipment window

- .github/workflows/build.yml
- build.gradle
- sonar-project.properties
This commit creates the Gradle task upgradeCoreVersion to upgrade the Core version of a project based on the type property passed to the task. If type is release, the task updates the version to the next release, and if type is hotfix, it updates the version to the next hotfix. The task also updates the version in two AD_MODULE.xml files, and the build.gradle file with the new values. If the format of the AD_MODULE.xml files was changed, the task throws a GradleException.
> Feature EPL-572: Upgrade Core Version with Gradle Task

- modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/actionHandler/AddPaymentActionHandler.java
> Issue #168: Remove wrong validation

- src/org/openbravo/erpCommon/ad_forms/MaterialReceiptPending.java
EPL-594: The connection is closed in the finnaly block. Identation has been fixed
> Issue #197: processPurchaseOrder causes idle in transactions

- src/org/openbravo/event/PaidStatusEventHandler.java
correction when a reconciliation is created and set in the transaction
> Issue #204: correction when a reconciliation is created

- modules_core/com.smf.securewebservices/web/com.smf.securewebservices/doc/doc.yaml
> Issue #215: Modify Swagger, updating and adding parameters

- src/org/openbravo/erpCommon/ad_reports/ReportInvoiceCustomerDimensionalAnalysesJRFilter.html
> Issue #219: Fix to download report from firefox.

- modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/event/FIN_FinaccTransactionEventListener.java
> Issue #148: Change the error message thrown

- build.xml
- src-db/database/build.xml
- src/org/openbravo/service/system/SystemDeleteClientTask.java
- src/org/openbravo/service/system/SystemService.java
EPL-1146: Also fixed issues with source format modules with dependencies to JAR format modules unable to find their tables.
> Issue #264: Added deleted client gradle task process.

- modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/process/ob-parameter-window-view.js
> Issue #282: Deleted unnesesary parenthesis

- modules_core/com.smf.jobs.defaults/src-db/database/sourcedata/AD_TABLE.xml
> Issue #289: Fixed logic for the invoice terms of orders

- src/org/openbravo/erpCommon/ad_actionButton/Posted.java
EPL-1226: Applying suggested solution. Doing the unposting as was done before.
Also, applied Etendo code formatting, utilizing StringUtils
> Issue #301: Fix unposting for different days/orgs

- src/org/openbravo/common/actionhandler/createlinesfromprocess/CreateInvoiceLinesFromProcess.java
> Issue #310: Fix creation order of invoice lines from shipment lines

- src/org/openbravo/common/actionhandler/CopyFromOrdersActionHandler.java
> Issue #343: Add 'refreshParent' property to the response actions

- pipelines/unittests/Jenkinsfile
- pipelines/unittests/JenkinsfileOracle
and add information about the stack in the mail body
> Hotfix ETO-308: Upgrade tomcat version in pipelines

- src-db/database/model/tables/AD_SEQUENCE.xml
> Issue #256: Unchanged Index is exported in template

- src-test/src/org/openbravo/test/StandaloneTestSuite.java
- src-test/src/org/openbravo/test/accounting/PostedNoDocConfigTest.java
- src/org/openbravo/financial/ResetAccounting.java
> Issue #369: Correct error handling when deleting accounting data

- src/org/openbravo/erpCommon/ad_callouts/SE_Invoice_BPartner.java
> Issue #297: Fix blank callout messages

- pipelines/unittests/Jenkinsfile
- pipelines/unittests/JenkinsfileOracle
- pipelines/unittests/utils/infoCommit.groovy
- pipelines/unittests/utils/stackConfig.groovy
Add html formatting to mail body
> Hotfix ETO-314: Remove 'Restart Environment' stage from pipelines

- .github/workflows/build.yml
- src/org/openbravo/erpCommon/ad_reports/ReportGeneralLedger_data.xsql
Sorting will change if Simple G/L Journal entry records exist
> Feature EPL-1469: Change General Ledger ordering

- .github/workflows/build.yml
- build.gradle
- gradle.properties.template
Add message in build.yml action
> Feature ETO-325: Modify Sonarqube and Jacoco properties

- src/org/openbravo/erpCommon/ad_forms/DocInternalConsumption.java
Issue #306: added the fix to allow the custom accounting while posting internal consumption document
EPL-1238
> Issue #306: fix custom accounting for internal consumption

- pipelines/unittests/Jenkinsfile
- tests.gradle
EPL-1530: Add mockito dependency
> Issue #414: Set resources test dir for 'modules' and 'modules_core' 

- pipelines/unittests/Jenkinsfile
- pipelines/unittests/build-update.sh
> Hotfix ETO-346: Change access_token for update commit status

- modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/form/ob-view-form.js
EPL-530: Remove blur in combobox item to prevent set changes on this and abnormally execution of callouts
> Issue #270: Fix JS function to prevent abnormally callouts execution.

- src/org/openbravo/erpCommon/ad_forms/AcctServer.java
> Issue #442: Bugfix found in accouting process in deprecated code (C_ACCTSCHEMA_PROCESS)

- modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/process/FIN_PaymentProcess.java
- src-test/src/org/openbravo/advpaymentmngt/test/ReversePaymentTest.java
- src-test/src/org/openbravo/advpaymentmngt/test/TestUtility.java
- src-test/src/org/openbravo/test/StandaloneTestSuite.java
ETP-109: Fixed Reverse Payment process of payments created on fully payment sales invoices to set isInvoicePaid in false in new payment detail created.
> Issue #445: Fix Reverse Payment process of fully payment invoices.

- src/org/openbravo/erpCommon/ad_process/HeartbeatProcess.java
- src/org/openbravo/listeners/HeartbeatListener.java
Refactor parseResponse to handle JSON arrays and objects for alerts
> Feature EPL-1720: Schedule HeartbeatProcess with Tomcat startup

- modules_core/com.smf.jobs.defaults/src/com/smf/jobs/defaults/CloneInvoiceHook.java
- pipelines/unittests/Jenkinsfile
- pipelines/unittests/JenkinsfileOracle
- pipelines/unittests/build-update.sh
- pipelines/unittests/utils/infoCommit.groovy
- pipelines/unittests/utils/stackConfig.groovy
- sonar-project.properties
- src-test/src/org/openbravo/test/StandaloneTestSuite.java
- src-test/src/org/openbravo/test/invoice/CallCloneInvoice.java
- src-test/src/org/openbravo/test/invoice/CloneInvoiceTest.java
ETP-50: Truncate invoice date and accounting date to prevent generates a payment as an prepayment.
> Issue #345: Fix clone invoice hook to truncate dates.

- modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/filterexpression/TransactionAddPaymentDefaultValues.java
ETP-377: The function in charge of converting the representation of the number entered by the user to a secure format has been modified. This representation is in string format and needs to be corrected in some cases. However, the implementation of the function did not support scientific notation, so it has been modified to support it.
> Issue #481: Support for scientific notation in bigdecimal conversion

- src/org/openbravo/erpCommon/ad_reports/ReportBudgetGenerateExcel_data.xsql
> Issue #366: Fix error in period when printing quotation

- build.gradle
- pipelines/unittests/Jenkinsfile
Add jacocoRootReport task in build.gradle
> Feature ETP-296: Add stage in tests pipeline for run Sonarqube

- modules_core/org.openbravo.client.application/src-db/database/model/triggers/OBUIAPP_PROCESS_MOD_TRG.xml
- modules_core/org.openbravo.client.application/src-test/org/openbravo/client/application/test/db/model/triggers/OBUIAPP_ProcessTest.java
- modules_core/org.openbravo.client.application/src-test/org/openbravo/client/application/test/db/model/triggers/ProcessTest.java
- src-test/src/org/openbravo/test/StandaloneTestSuite.java
> Issue #291: Added missing triggers in Process Definition window.

- modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/process/ob-pick-and-execute-grid.js
ETP-691: When a filter is applied to an OBPickAndExecuteGrid and then a record is selected, when scrolling, the dataSource.transformRequest function checks the selected records and if they are not within the request criteria, it tries to add them. Here, information about the grid parameters is lost, so corrections have been made to recover them.
> Issue #516: Fix for OBPickAndExecuteGrid parameters

- modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/process/ob-pick-and-execute-grid.js
> Issue #516: Fix P&E filter loss

- src/org/openbravo/materialmgmt/InvoiceGeneratorFromGoodsShipment.java
> Issue #529: Add user contact in Invoice creation from Goods Shipment 

- src-test/src/org/openbravo/erpCommon/ad_callouts/LandedCostTypeTest.java
- src-test/src/org/openbravo/test/StandaloneTestSuite.java
- src/org/openbravo/erpCommon/ad_callouts/SL_LandedCost_Cost_Type.java
> Issue #489: Automatic update of Landed Cost Distribution Algorithm

- pipelines/unittests/JenkinsfileOracle
An oracle image is added inside the dynamic agent to create a dynamic database to be used during compilation
> Feature ETP-125: Add dynamic oracle agent in test pipeline

- src-db/database/model/functions/M_INTERNAL_CONSUMPTION_POST1.xml
> Issue #565: Add period validation to Internal Consumption process

- src-test/src/org/openbravo/test/stockReservation/PrereservationTest.java
- src/org/openbravo/common/actionhandler/ManagePrereservationActionHandler.java
> Issue #553: Fix reservation status in purchase order pre-reservation

- src-test/src/com/etendoerp/advpaymentmngt/EtendoComponentProviderTest.java
- src-test/src/com/etendoerp/advpaymentmngt/actionHandler/PaymentExecutionProcessActionHandlerTest.java
- tests.gradle
Test Path Update:
Added the path to the Groovy test files for the module_core:
> Feature ETP-1153: Add unit tests

- src/org/openbravo/common/actionhandler/ManagePrereservationActionHandler.java
> Issue #553: Fix pre-reservation reprocessing to avoid error

- pipelines/unittests/Jenkinsfile
- No changes to imports or dependencies were made.
- No endpoint changes were introduced.
- Modified shell command within the Jenkins pipeline:
```groovy
sh "./gradlew sonar -Dsonar.inclusions=**/*.java -Dsonar.exclusions=${sourceExclusions} --stacktrace --info"
```
- **Details**: The `sonar` Gradle task now includes specific inclusions for Java files and exclusions based on `modulesCoreExclusions`.
- No changes in types or interfaces affecting the public API.
- There are no breaking changes requiring user attention.
- **Gradle Task Execution**:
- The modified execution of the `sonar` task now includes dynamic exclusions:
```groovy
def modulesCoreExclusions = [
"com.smf.userinterface.skin.legacy",
"org.openbravo.client.widgets",
"org.openbravo.client.htmlwidget", …
```
> Feature ETP-1269: Add parameter inclusion in Sonar execution

- src/org/openbravo/erpCommon/ad_callouts/SE_Order_BPartner_data.xsql
ETP-1279
**The issue of bundle tests not passing is being addressed.**
> Issue #631: Prioritize warehouse selection based on priority

- modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/dao/AdvPaymentMngtDao.java
- modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/filterexpression/TransactionAddPaymentDisplayLogics.java
- modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/utility/APRMConstants.java
- modules_core/org.openbravo.advpaymentmngt/web/org.openbravo.advpaymentmngt/js/ob-aprm-addPayment.js
ETP-1242: Fixed exception triggered when switching from business partners(Received From) in the popup to add payments from transactions in financial account.
> Issue #615: Allows business partner selection when adding payments

- src/org/openbravo/erpCommon/utility/MimeTypeUtil.java
> Issue #662: Fix BMP image MIME type detection

- src/org/openbravo/common/hooks/PrintControllerHookManager.java
- src/org/openbravo/erpCommon/utility/reporting/printing/PrintController.java
>  Issue #669: Fix print hooks when more than one is present

- src/org/openbravo/common/hooks/PrintControllerHookManager.java
- src/org/openbravo/erpCommon/utility/reporting/printing/PrintController.java
> Issue #669: Fix print hooks when more than one is present

- src-db/database/model/functions/C_COMMISSION_PROCESS.xml
> Issue #680: Fix incorrect commission calculation

- src-db/database/model/functions/C_ORDER_POST1.xml
> Issue #682: Fix Reservation Status after Reactivating and Booking SO

- pipelines/unittests/Jenkinsfile
- pipelines/unittests/JenkinsfileOracle
In this Pr the namespaces of the dynamic pods are set to match the new Jenkins server
> Feature ETP-1547: Edit Namespaces

- src/org/openbravo/erpCommon/ad_reports/CustomerStatement.jrxml
> Issue #704: Improve localization and layout in CustomerStatement report

- modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/actionHandler/FundsTransferActionHandler.java
> Issue #709: Add exchange rates when doing funds transfers

- src/org/openbravo/common/actionhandler/copyfromorderprocess/UpdatePricesAndAmounts.java
> Issue #717: Fix Alternative Taxable Amount on Copy From Order process

- src/org/openbravo/erpCommon/ad_forms/AcctServer.java
> Issue #725: Change the post process to keep in mind when a payment is also related to an order.

- src-db/database/model/functions/C_INVOICE_POST.xml
- src-db/database/model/functions/M_INOUT_POST.xml
> Issue #739: Fix quantities and status of orders and inout documents

- src-db/database/model/functions/M_GET_OFFERS_NAME.xml
> Issue #741: Fix display name of offers in copy lines popup

- src-db/database/model/functions/M_PROMOTION_CALCULATE.xml
- src/org/openbravo/erpCommon/businessUtility/PriceAdjustment.java
> Issue #751: Apply discounts where included Characteristics is set to All.

- src-db/database/model/functions/M_INOUT_POST.xml
- src-db/database/model/tables/C_INVOICELINE.xml
- src-db/database/model/tables/M_INOUTLINE.xml
- src-db/database/model/views/M_INOUTLINE_TOTALINVOICED_V.xml
> Issue #750: Fix InOut process performance and returns invoice percent

- src/org/openbravo/erpCommon/ad_forms/AcctServer.java
> Issue #761: Fix suspense entry when payment amount is zero

- src-db/database/model/functions/M_PROMOTION_ADD.xml
- src-db/database/model/functions/M_PROMOTION_CALCULATE.xml
> Issue #762: Fix incorrect calculation of Alternative Taxable Base when applying promotions

- build.xml
- pipelines/unittests/Jenkinsfile
> Issue #771: Add conditional property for extra modules location

- modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/process/ob-pick-and-execute-grid.js
> Issue #774: Fix dataPageSize to use window-specific value

- modules_core/org.openbravo.client.application/src/org/openbravo/client/application/report/BaseReportActionHandler.java
> Issue #780: Prevent error in HTML report links

- src/org/openbravo/erpCommon/ad_callouts/SE_Locator_Activate.java
> Issue #787: Change hqlQuery to group all OR conditions under the storageBinId.

- modules_core/org.openbravo.advpaymentmngt/web/org.openbravo.advpaymentmngt/js/ob-aprm-addPayment.js
> Issue #790: Add a check for GLItems when adding payments.
